[package]
name = "altius-interpreter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
altius-core = { path = "../core" }
rustc-hash = "1.1.0"

[dev-dependencies]
rayon = "*"
